import React,{useMemo,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,Routes,Route,Link,useNavigate} from "react-router-dom";
import {Rnd} from "react-rnd";
import {toPng} from "html-to-image";
import {Menu,X,ArrowRight,Upload,RotateCcw,Undo2,Redo2,Trash2,Download,Phone,Mail,MapPin,MessageCircle,Plus,Edit3,Save,Search} from "lucide-react";
import "./style.css";
import logo from "./assets/arizona-logo.svg";

const products=[
{id:1,name:"Milano Cloud Sofa",cat:"Sofa",price:"₹85,000",size:"8' x 3'",material:"Premium Fabric + Wood",color:"Beige / Grey",desc:"A soft, contemporary luxury sofa designed for refined living spaces.",img:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80"},
{id:2,name:"Aurora Platform Bed",cat:"Bed",price:"₹72,000",size:"6' x 6.5'",material:"Upholstery + Plywood",color:"Warm Grey / Beige",desc:"Modern upholstered bed with a calm, premium silhouette.",img:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"},
{id:3,name:"Linea Wardrobe",cat:"Wardrobe",price:"₹95,000",size:"8' x 7'",material:"HDHMR + Veneer",color:"Oak / Charcoal",desc:"Customized storage with clean lines and elegant detailing.",img:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80"},
{id:4,name:"Frame TV Unit",cat:"TV Unit",price:"₹48,000",size:"7' x 1.5'",material:"HDHMR + Laminate",color:"Walnut / Beige",desc:"Minimal entertainment unit designed for modern interiors.",img:"https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1200&q=80"},
{id:5,name:"Nova Dining Table",cat:"Dining Table",price:"₹68,000",size:"6' x 3'",material:"Solid Wood + Stone",color:"Natural Oak",desc:"A sculptural dining table for memorable everyday gatherings.",img:"https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80"},
{id:6,name:"Arc Lounge Chair",cat:"Chairs",price:"₹22,000",size:"30 x 30 in",material:"Fabric + Metal",color:"Sand / Black",desc:"Comfortable accent seating with a contemporary profile.",img:"https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=80"}
];
const cats=["Sofa","Bed","Wardrobe","TV Unit","Dining Table","Chairs","Lighting","Decor","Customized Furniture"];
const projects=[
["Residential Villa","https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80"],
["Luxury Bedroom","https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=80"],
["Modern Living","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80"],
["Contemporary Kitchen","https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1400&q=80"],
["Hotel Interior","https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80"],
["Modern Facade","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80"]
];

function Layout({children}){const[open,setOpen]=useState(false);return <><header><Link className="brand" to="/" aria-label="Arizona Furniture Home"><img src={logo} alt="Arizona Furniture"/></Link><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"show":""}>{["Home","Furniture","Design Your Room","Interior Projects","Exterior Projects","About","Contact","Admin"].map(x=><Link key={x} to={"/"+(x==="Home"?"":x.toLowerCase().replaceAll(" ","-"))} onClick={()=>setOpen(false)}>{x}</Link>)}</nav></header>{children}<footer><div><b>ARIZONA INTERIOR EXTERIOR</b><p>Designing Spaces. Creating Experiences.</p></div><p>© 2026 Arizona Interior Exterior</p></footer><a className="whatsapp" href="https://wa.me/918155964677" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle/></a></>}

const Section=({eyebrow,title,children})=><section className="section"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{children}</section>;

function Home(){return <><div className="hero"><div className="heroText"><p className="eyebrow">PREMIUM INTERIORS • CUSTOM FURNITURE</p><h1>ARIZONA<br/><i>INTERIOR EXTERIOR</i></h1><p>Designing Spaces. Creating Experiences.</p><div className="actions"><Link className="btn" to="/furniture">Explore Furniture <ArrowRight/></Link><Link className="btn ghost" to="/design-your-room">Design Your Room</Link></div></div></div>
<Section eyebrow="WHAT WE DO" title="Designed around the way you live."><div className="grid three">{["Interior Design","Exterior Design","Customized Furniture"].map((x,i)=><div className="card service" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Thoughtful design, precise detailing and premium materials for spaces with a lasting identity.</p></div>)}</div></Section>
<Section eyebrow="FURNITURE" title="Made for your space."><div className="categories">{cats.map(c=><Link key={c} to={"/furniture?cat="+encodeURIComponent(c)}>{c}<ArrowRight size={16}/></Link>)}</div></Section>
<Section eyebrow="FEATURED" title="Signature furniture collection"><ProductGrid limit={3}/><div className="center"><Link className="textlink" to="/furniture">View all furniture <ArrowRight/></Link></div></Section>
<Section eyebrow="PROJECTS" title="Spaces we are proud to create"><div className="projectGrid">{projects.slice(0,4).map(([n,i])=><div className="project" key={n} style={{backgroundImage:`url(${i})`}}><span>{n}</span></div>)}</div></Section>
<Section eyebrow="THE ARIZONA WAY" title="From idea to installation."><div className="steps">{["Consult & Understand","Design & Visualize","Craft & Execute","Deliver & Experience"].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3></div>)}</div></Section>
<ContactCTA/></>}

function ProductGrid({limit,cat}){let data=cat?products.filter(p=>p.cat===cat):products; if(limit)data=data.slice(0,limit);return <div className="productGrid">{data.map(p=><article className="product" key={p.id}><img src={p.img}/><div className="productBody"><small>{p.cat}</small><h3>{p.name}</h3><b>{p.price}</b><p>{p.size} · {p.material}</p><div className="row"><Link className="mini" to={"/furniture/"+p.id}>View Details</Link><Link className="mini dark" to="/design-your-room">Design In My Room</Link></div></div></article>)}</div>}

function Furniture(){const params=new URLSearchParams(location.search);const[cat,setCat]=useState(params.get("cat")||"All");return <Section eyebrow="COLLECTION" title="Furniture with character."><div className="filters"><button className={cat==="All"?"active":""} onClick={()=>setCat("All")}>All</button>{cats.map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}</div><ProductGrid cat={cat==="All"?null:cat}/></Section>}

function Designer(){
 const[file,setFile]=useState(null),[items,setItems]=useState([]),[history,setHistory]=useState([[]]),[hIndex,setHIndex]=useState(0),ref=useRef();
 const commit=(next)=>{const h=[...history.slice(0,hIndex+1),next];setHistory(h);setHIndex(h.length-1);setItems(next)};
 const add=p=>commit([...items,{uid:Date.now()+Math.random(),...p,x:70,y:70,w:220,h:150,rot:0}]);
 const update=(uid,patch)=>setItems(v=>v.map(i=>i.uid===uid?{...i,...patch}:i));
 const remove=uid=>commit(items.filter(i=>i.uid!==uid));
 const saveCurrent=()=>commit(items);
 const undo=()=>{if(hIndex>0){setHIndex(hIndex-1);setItems(history[hIndex-1])}};
 const redo=()=>{if(hIndex<history.length-1){setHIndex(hIndex+1);setItems(history[hIndex+1])}};
 const download=async()=>{if(!ref.current)return;const url=await toPng(ref.current,{cacheBust:true});const a=document.createElement("a");a.href=url;a.download="arizona-room-design.png";a.click()};
 return <div className="designerPage"><div className="designerHead"><div><div className="eyebrow">INTERACTIVE ROOM STUDIO</div><h2>Design Your Room</h2><p>Upload your room, add Arizona furniture, then drag, resize and rotate.</p></div><div className="toolBtns"><button onClick={undo}><Undo2/>Undo</button><button onClick={redo}><Redo2/>Redo</button><button onClick={()=>commit([])}><RotateCcw/>Reset</button><button className="download" onClick={download}><Download/>Download</button></div></div>
 <div className="studio"><aside><label className="upload"><Upload/><b>{file?"Change Room Photo":"Upload Room Photo"}</b><input type="file" accept="image/*" onChange={e=>e.target.files[0]&&setFile(URL.createObjectURL(e.target.files[0]))}/></label><h3>Furniture Library</h3>{products.map(p=><button className="library" key={p.id} onClick={()=>add(p)}><img src={p.img}/><span>{p.name}<small>{p.cat}</small></span><Plus/></button>)}</aside>
 <main className="canvasWrap"><div className="canvas" ref={ref} style={{backgroundImage:file?`url(${file})`:undefined}}>{!file&&<div className="emptyCanvas"><Upload size={42}/><h3>Upload a room image to begin</h3><p>Your room photo becomes the design background.</p></div>}{items.map(it=><Rnd key={it.uid} size={{width:it.w,height:it.h}} position={{x:it.x,y:it.y}} bounds="parent" onDragStop={(e,d)=>update(it.uid,{x:d.x,y:d.y})} onResizeStop={(e,dir,el,delta,pos)=>update(it.uid,{w:parseInt(el.style.width),h:parseInt(el.style.height),...pos})}><div className="overlay" style={{transform:`rotate(${it.rot}deg)`}}><img src={it.img}/><div className="overlayBar"><button onClick={()=>update(it.uid,{rot:it.rot-15})}>↺</button><button onClick={()=>update(it.uid,{rot:it.rot+15})}>↻</button><button onClick={()=>remove(it.uid)}><Trash2 size={15}/></button></div></div></Rnd>)}</div><p className="hint">Tip: Drag products into position. Use corner handles to resize and ↺ / ↻ to rotate.</p></main></div></div>
}

function Projects({type}){let data=type==="Exterior"?projects.slice(5):projects.slice(0,5);return <Section eyebrow={type.toUpperCase()+" PORTFOLIO"} title={type==="Exterior"?"Architecture that makes a statement.":"Interiors with a story to tell."}><div className="projectGrid large">{data.map(([n,i])=><div className="project" key={n} style={{backgroundImage:`url(${i})`}}><span>{n}</span></div>)}</div><div className="beforeAfter"><div><b>BEFORE</b><div className="placeholder">Original Space</div></div><div><b>AFTER</b><div className="placeholder darkp">Arizona Transformation</div></div></div></Section>}

function About(){return <><Section eyebrow="OUR STORY" title="ARIZONA INTERIOR EXTERIOR"><div className="about"><p>We create spaces that feel personal, perform beautifully and stand the test of time. Arizona brings interior design, exterior design and customized furniture together under one thoughtful design approach.</p><p>From the first sketch to final installation, our focus is on detail, material quality and an experience tailored to every client.</p></div></Section><Section eyebrow="OUR PHILOSOPHY" title="Quiet luxury. Clear thinking. Lasting design."><div className="grid three">{["Personal","Precise","Premium"].map(x=><div className="card service"><h3>{x}</h3><p>Every decision is shaped around your lifestyle, your space and the details that matter.</p></div>)}</div></Section></>}

function ContactCTA(){return <section className="contactCTA"><div><div className="eyebrow">START A PROJECT</div><h2>Let's create your next space.</h2><p>Tell us about your home, office, hotel or custom furniture requirement.</p></div><Link className="btn" to="/contact">Contact Arizona <ArrowRight/></Link></section>}

function Contact(){return <Section eyebrow="GET IN TOUCH" title="Let's talk about your space."><div className="contactGrid"><form onSubmit={e=>{e.preventDefault();alert("Thank you! Your enquiry has been received by Arizona Furniture. We will contact you shortly.")}}><input placeholder="Your Name" required/><input type="email" placeholder="Email Address" required/><input placeholder="Phone Number"/><textarea placeholder="Tell us about your project" rows="6"/><button className="btn">Send Enquiry <ArrowRight/></button></form><div className="contactInfo"><p><Phone/> <a href="tel:+918155964677">+91 81559 64677</a></p><p><Mail/> <a href="mailto:arizonainterior369@gmail.com">arizonainterior369@gmail.com</a></p><p><MapPin/> 238, Meridian Business Centre, Lajamni Chowk, Mota Varachha, Surat – 394101</p><p><MessageCircle/> <a href="https://wa.me/918155964677" target="_blank" rel="noreferrer">WhatsApp: +91 81559 64677</a></p><div className="map">Google Maps<br/>Location Placeholder</div></div></div></Section>}

function Admin(){const[tab,setTab]=useState("Products"),[data,setData]=useState(products),[name,setName]=useState("");const add=()=>{if(!name)return;setData([...data,{id:Date.now(),name,cat:"Customized Furniture",price:"₹0",size:"Custom",material:"Custom",color:"Custom",desc:"",img:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80"}]);setName("")};return <div className="admin"><aside><b>ARIZONA ADMIN</b>{["Products","Categories","Projects","Enquiries","Room Uploads","Saved Designs"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</aside><main><div className="adminTop"><h2>{tab}</h2><button className="btn" onClick={add}><Plus/> Add Product</button></div>{tab==="Products"?<><div className="adminAdd"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New product name"/><button onClick={add}>Add</button></div><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Actions</th></tr></thead><tbody>{data.map(p=><tr><td>{p.name}</td><td>{p.cat}</td><td>{p.price}</td><td><button onClick={()=>setData(data.filter(x=>x.id!==p.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></>:<div className="emptyAdmin"><Save size={36}/><h3>{tab} management ready</h3><p>Connect this module to your cloud database and storage in the next phase.</p></div>}</main></div>}

function App(){return <BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/furniture" element={<Furniture/>}/><Route path="/design-your-room" element={<Designer/>}/><Route path="/interior-projects" element={<Projects type="Interior"/>}/><Route path="/exterior-projects" element={<Projects type="Exterior"/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<Home/>}/></Routes></Layout></BrowserRouter>}
createRoot(document.getElementById("root")).render(<App/>);